/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "stdint.h"
#include "platform_types.h"

// register address

#define  RCC_BASE      0X40021000
#define  GPIOA_BASE    0X40010800
#define  GPIOA_CRH     *( vuint32_t *)(GPIOA_BASE + 0X04)
#define  GPIOA_ODR     *( vuint32_t *)(GPIOA_BASE + 0X0C)
#define  RCC_APB2ENR   *( vuint32_t *)(RCC_BASE + 0X18)

// BIT FIELDS

#define  RCC_IOPEN      (1 << 2)
#define  GPIOA13        (1UL << 13)

//**

typedef union {
	vuint32_t   all_fields;
	struct {
		vuint32_t   reserved : 13;
		vuint32_t   P_13 : 1;
	}Pin;
} R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0X0C);


int main(void)
{
	RCC_APB2ENR |= RCC_IOPEN;
	GPIOA_CRH  &= 0XFF0FFFFF;
	 GPIOA_ODR |= 0X00200000;
	 while(1)
	 {
		int i;
		 R_ODR -> Pin.P_13 =1;
		 for( i=0 ; i<1000 ; i++); // delay
		 R_ODR -> Pin.P_13 =0;
		 for( i=0 ; i<1000 ; i++); // delay
	 }


}
